kind: pipeline
name: pipeline-example-maven

steps:
  - name: publish
    image: plugins/docker
    settings:
      mirror: https://registry-vpc.cn-shanghai.aliyuncs.com
      registry: registry-vpc.cn-shanghai.aliyuncs.com # 仓库
      repo: registry-vpc.cn-shanghai.aliyuncs.com/qcy_docker/chat # docker仓库地址
      username: qiancaoyu316
      password: QIANcaoyu316
      tags:
        - ${DRONE_BUILD_NUMBER}
  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: 62.234.186.57
      username: root
      password: QIANcaoyu316
      port: 22
      environment:
        PWD: docker_password
      script:
        - docker login --username=qiancaoyu316 --password=QIANcaoyu316 registry-vpc.cn-shanghai.aliyuncs.com
        - docker pull registry.cn-shanghai.aliyuncs.com/qcy_docker/chat:${DRONE_BUILD_NUMBER}
        - docker stop chat
        - docker rm chat
        - docker run -itd --name chat --network chat -e spring.profile.active=prod registry.cn-shanghai.aliyuncs.com/qcy_docker/chat:${DRONE_BUILD_NUMBER}
